[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend_clean && pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "cd backend_clean && uvicorn main:app --host 0.0.0.0 --port $PORT"
